baseURL = "https://dashdashzako.github.io/paperback-demo/"
languageCode = "en-us"
title = "Paperback Theme Showcase"
theme = "paperback"
disableKinds = ["section", "taxonomy", "term", "RSS"]

[params]
  AuthorName = "dashdashzako"
  GithubUsername = "dashdashzako"
  Tagline = "Minimalist theme for Hugo"
  mainSections = ["post"]
